=== adminicg/opentracker/data/opentracker.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.0 (http://www.xmlspy.com) by gr (gr) -->
<!--OpenTracker Configuration file DTD
	Vienna University of Technology
	Gerhard Reitmayr reitmayr@cg.tuwien.ac.at-->
<!-- Entitiy definitions for the different classes of elements
      element names have to be seperated by |  -->
<!ENTITY % ConfigElements "NetworkSinkConfig?,VideoConfig?,NetworkSourceConfig?,ConsoleConfig?,IntertraxConfig?">
<!ENTITY % EventNodes "NetworkSink | EventTransformation | EventVirtualTransformation | VideoSource | TestSource | NetworkSource | EventQueue | ConsoleSink | IntertraxSource | Ref">
<!ENTITY % QueueNodes "QueueTransformation | QueueVirtualTransformation | EventQueue | Ref">
<!ENTITY % TimeNodes "TimeTransformation | TimeVirtualTransformation | Ref">
<!ENTITY % AllNodes "%EventNodes; | %QueueNodes; | %TimeNodes;">
<!-- general elements that do not map to nodes -->
<!ELEMENT OpenTracker (configuration, (%AllNodes;)+)>
<!ELEMENT configuration (%ConfigElements;)>
<!-- basic elements
there are several versions for the different interfaces 
Event prefix defines that the node implements an EventGenerator interface
Queue prefix defines that the node implements an EventQueue interface
Time prefix defines that the node implements an TimeDependend interface -->
<!ELEMENT Ref EMPTY>
<!ATTLIST Ref
	USE IDREF #REQUIRED
>
<!-- general transformation elements -->
<!ELEMENT EventTransformation (%EventNodes;)>
<!ATTLIST EventTransformation
	DEF ID #IMPLIED
	translation CDATA "0 0 0"
	scale CDATA "1 1 1"
	rotationtype (quaternion | matrix | euler | axisangle) "quaternion"
	rotation CDATA "0 0 0 1"
>
<!ELEMENT EventVirtualTransformation (%EventNodes;)>
<!ATTLIST EventVirtualTransformation
	DEF ID #IMPLIED
	translation CDATA "0 0 0"
	scale CDATA "1 1 1"
	rotationtype (quaternion | matrix | euler | axisangle) "quaternion"
	rotation CDATA "0 0 0 1"
>
<!ELEMENT QueueTransformation (%QueueNodes;)>
<!ATTLIST QueueTransformation
	DEF ID #IMPLIED
	translation CDATA "0 0 0"
	scale CDATA "1 1 1"
	rotationtype (quaternion | matrix | euler | axisangle) "quaternion"
	rotation CDATA "0 0 0 1"
>
<!ELEMENT QueueVirtualTransformation (%QueueNodes;)>
<!ATTLIST QueueVirtualTransformation
	DEF ID #IMPLIED
	translation CDATA "0 0 0"
	scale CDATA "1 1 1"
	rotationtype (quaternion | matrix | euler | axisangle) "quaternion"
	rotation CDATA "0 0 0 1"
>
<!ELEMENT TimeTransformation (%TimeNodes;)>
<!ATTLIST TimeTransformation
	DEF ID #IMPLIED
	translation CDATA "0 0 0"
	scale CDATA "1 1 1"
	rotationtype (quaternion | matrix | euler | axisangle) "quaternion"
	rotation CDATA "0 0 0 1"
>
<!ELEMENT TimeVirtualTransformation (%TimeNodes;)>
<!ATTLIST TimeVirtualTransformation
	DEF ID #IMPLIED
	translation CDATA "0 0 0"
	scale CDATA "1 1 1"
	rotationtype (quaternion | matrix | euler | axisangle) "quaternion"
	rotation CDATA "0 0 0 1"
>
<!-- EventQueue stores a queue of size length of the last received events.
It implements the EventGenerator as well as the EventQueue interface. -->
<!ELEMENT EventQueue (%EventNodes;)>
<!ATTLIST EventQueue
	DEF ID #IMPLIED
	length CDATA "1"
>
<!-- Source and Sink nodes grouped after functionality -->
<!-- network sender elements -->
<!ELEMENT NetworkSinkConfig EMPTY>
<!ATTLIST NetworkSinkConfig
	name CDATA #REQUIRED
>
<!ELEMENT NetworkSink (%EventNodes;)>
<!ATTLIST NetworkSink
	DEF ID #IMPLIED
	name CDATA #REQUIRED
	number CDATA #REQUIRED
	multicast-address CDATA #REQUIRED
	port CDATA #REQUIRED
>
<!--network receiver elements, acting as sources-->
<!ELEMENT NetworkSourceConfig EMPTY>
<!ELEMENT NetworkSource EMPTY>
<!ATTLIST NetworkSource
	DEF ID #IMPLIED
	number CDATA #REQUIRED
	multicast-address CDATA #REQUIRED
	port CDATA #REQUIRED
>
<!-- video source elements -->
<!ELEMENT VideoConfig EMPTY>
<!ATTLIST VideoConfig
	camera-parameter CDATA #REQUIRED
>
<!ELEMENT VideoSource EMPTY>
<!ATTLIST VideoSource
	DEF ID #IMPLIED
	tag-file CDATA #REQUIRED
	vertex CDATA #REQUIRED
>
<!-- test source elements -->
<!ELEMENT TestSource EMPTY>
<!ATTLIST TestSource
	DEF ID #IMPLIED
	frequency CDATA "1"
	offset CDATA "0"
>
<!-- console based output elements -->
<!ELEMENT ConsoleConfig EMPTY>
<!ATTLIST ConsoleConfig
	headerline CDATA ""
	interval CDATA "10"
>
<!ELEMENT ConsoleSink (%EventNodes;)>
<!ATTLIST ConsoleSink
	DEF ID #IMPLIED
	comment CDATA ""
>
<!-- Intertrax source elements -->
<!ELEMENT IntertraxConfig EMPTY>
<!ELEMENT IntertraxSource EMPTY>
<!ATTLIST IntertraxSource
	DEF ID #IMPLIED
>

=== adminicg/opentracker/data/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v3.0 (http://www.xmlspy.com) by gr (gr) -->
<!--simple test configuration for the new tracker serve system-->
<!DOCTYPE OpenTracker SYSTEM "opentracker.dtd">
<OpenTracker>
	<configuration>
		<NetworkSinkConfig name="Test Server"/>
		<ConsoleConfig interval="20"/>
	</configuration>
	<NetworkSink name="test station 1" number="1" multicast-address="224.100.200.102" port="12347">
		<ConsoleSink comment="Test Console Output">
			<EventTransformation translation="0 0 2">
				<TestSource frequency="10"/>
			</EventTransformation>
		</ConsoleSink>
	</NetworkSink>
</OpenTracker>

=== adminicg/opentracker/data/simple_network_server.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OpenTracker SYSTEM "opentracker.dtd">
<OpenTracker>
  <configuration>
    <ConsoleConfig headerline="Sample Output" interval="1"/>
  </configuration>
  <ConsoleSink comment="Test Source 1">
    <EventTransform translation="1 1 1" scale="1 1 1"
    rotationtype="euler" rotation="0 0 0" DEF="trdata1">
      <TestSource frequency="100000" />
    </EventTransform>
  </ConsoleSink>
  <NetworkSink  mode="multicast" name="station name" number="1" multicast-address="224.0.0.10" port="12345" interface="192.168.2.100" >
    <Ref USE="trdata1" />
  </NetworkSink>
</OpenTracker>

=== adminicg/opentracker/data/network_client_viscenter_test_unicast.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OpenTracker SYSTEM "opentracker.dtd">
<OpenTracker>
  <configuration>
    <ConsoleConfig headerline="Network Test Client - VisCenter@ICG" interval="1"/>
  </configuration>
  <ConsoleSink comment="NetworkSource 0">
      <NetworkSource  mode="unicast" address="129.27.201.31" number="0"
      multicast-address="224.100.200.101" port="12346" />
  </ConsoleSink>
  <ConsoleSink comment="NetworkSource 1">
      <NetworkSource  mode="unicast" address="129.27.201.31" number="1"
      multicast-address="224.100.200.101" port="12346" />
  </ConsoleSink>
  <ConsoleSink comment="NetworkSource 2">
      <NetworkSource  mode="unicast" address="129.27.201.31" number="2"
      multicast-address="224.100.200.101" port="12346" />
  </ConsoleSink>
  <ConsoleSink comment="NetworkSource 3">
      <NetworkSource  mode="unicast" address="129.27.201.31" number="3"
      multicast-address="224.100.200.101" port="12346" />
  </ConsoleSink>
  <ConsoleSink comment="NetworkSource 4">
      <NetworkSource  mode="unicast" address="129.27.201.31" number="4"
      multicast-address="224.100.200.101" port="12346" />
  </ConsoleSink>
  <ConsoleSink comment="NetworkSource 5">
      <NetworkSource  mode="unicast" address="129.27.201.31" number="5"
      multicast-address="224.100.200.101" port="12346" />
  </ConsoleSink>
</OpenTracker>
