=== adminicg/opentracker/studierstube3/bin/apps/aeki/data/aeki.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by Manuel Linsmayer (proTech) -->
<xsd:schema targetNamespace="http://www.expersite.com/AEKI" xmlns="http://www.expersite.com/AEKI" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xsd:element name="furniture">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="component" maxOccurs="unbounded"/>
        <xsd:element ref="assembly"/>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:key name="ComponentInstanceKey">
      <xsd:selector xpath="component/instance"/>
      <xsd:field xpath="@name"/>
    </xsd:key>
    <xsd:key name="ConnectorKey">
      <xsd:selector xpath="component/connector"/>
      <xsd:field xpath="@name"/>
    </xsd:key>
  </xsd:element>
  <xsd:element name="component">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="shape"/>
        <xsd:element name="dimension" type="size3f"/>
        <xsd:element ref="connector" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="instance" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
            <xsd:attribute name="tracker" use="optional">
              <xsd:simpleType>
                <xsd:restriction base="xsd:int">
                  <xsd:minInclusive value="1"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:attribute>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="shape">
    <xsd:complexType>
      <xsd:choice>
        <xsd:element ref="cube"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="cube">
    <xsd:complexType>
      <xsd:all>
        <xsd:element name="rounded" minOccurs="0">
          <xsd:complexType>
            <xsd:all>
              <xsd:element name="radius">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:double">
                    <xsd:minInclusive value="0"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
            </xsd:all>
          </xsd:complexType>
        </xsd:element>
      </xsd:all>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="connector">
    <xsd:complexType>
      <xsd:complexContent>
        <xsd:extension base="coord3f">
          <xsd:attribute name="name" type="xsd:string" use="required"/>
        </xsd:extension>
      </xsd:complexContent>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="assembly">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element name="rotate">
          <xsd:complexType>
            <xsd:attribute name="axis" use="required">
              <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                  <xsd:enumeration value="xpos"/>
                  <xsd:enumeration value="xneg"/>
                  <xsd:enumeration value="zpos"/>
                  <xsd:enumeration value="zneg"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:attribute>
            <xsd:attribute name="angle" use="required">
              <xsd:simpleType>
                <xsd:restriction base="xsd:int">
                  <xsd:enumeration value="90"/>
                  <xsd:enumeration value="180"/>
                  <xsd:enumeration value="270"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:attribute>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="add-component">
          <xsd:complexType>
            <xsd:sequence minOccurs="0">
              <xsd:element name="connect" minOccurs="3" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="connector-ref">
                      <xsd:complexType>
                        <xsd:attribute name="name" type="xsd:string" use="required"/>
                      </xsd:complexType>
                      <xsd:keyref name="ConnectorKeyRef1" refer="ConnectorKey">
                        <xsd:selector xpath="."/>
                        <xsd:field xpath="@name"/>
                      </xsd:keyref>
                    </xsd:element>
                    <xsd:element name="connector-ref">
                      <xsd:complexType>
                        <xsd:attribute name="name" type="xsd:string" use="required"/>
                        <xsd:attribute name="componentRef" type="xsd:string" use="optional"/>
                      </xsd:complexType>
                      <xsd:keyref name="ConnectorKeyRef2" refer="ConnectorKey">
                        <xsd:selector xpath="."/>
                        <xsd:field xpath="@name"/>
                      </xsd:keyref>
                      <xsd:keyref name="ComponentInstanceKeyRef2" refer="ComponentInstanceKey">
                        <xsd:selector xpath="."/>
                        <xsd:field xpath="@componentRef"/>
                      </xsd:keyref>
                    </xsd:element>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
          </xsd:complexType>
          <xsd:keyref name="ComponentInstanceKeyRef1" refer="ComponentInstanceKey">
            <xsd:selector xpath="."/>
            <xsd:field xpath="@name"/>
          </xsd:keyref>
        </xsd:element>
      </xsd:choice>
      <xsd:attribute name="componentName" type="xsd:IDREF"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:simpleType name="unit">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="mm"/>
      <xsd:enumeration value="cm"/>
      <xsd:enumeration value="dm"/>
      <xsd:enumeration value="m"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="coord3f">
    <xsd:all>
      <xsd:element name="x" type="xsd:float"/>
      <xsd:element name="y" type="xsd:float"/>
      <xsd:element name="z" type="xsd:float"/>
    </xsd:all>
    <xsd:attribute name="unit" type="unit" use="required"/>
  </xsd:complexType>
  <xsd:complexType name="size3f">
    <xsd:all>
      <xsd:element name="width">
        <xsd:simpleType>
          <xsd:restriction base="xsd:float">
            <xsd:minExclusive value="0"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element name="height">
        <xsd:simpleType>
          <xsd:restriction base="xsd:float">
            <xsd:minExclusive value="0"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element name="depth">
        <xsd:simpleType>
          <xsd:restriction base="xsd:float">
            <xsd:minExclusive value="0"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
    </xsd:all>
    <xsd:attribute name="unit" type="unit" use="required"/>
  </xsd:complexType>
  <xsd:complexType name="vec3f">
    <xsd:all>
      <xsd:element name="x" type="xsd:float"/>
      <xsd:element name="y" type="xsd:float"/>
      <xsd:element name="z" type="xsd:float"/>
    </xsd:all>
  </xsd:complexType>
</xsd:schema>

=== adminicg/opentracker/studierstube3/bin/apps/aeki/data/smallbox2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.2 U (http://www.xmlspy.com) by Ponder (Vienna University of Technology) -->
<furniture xmlns="http://www.expersite.com/AEKI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.expersite.com/AEKI ../apps/aeki/data/aeki.xsd">
	<!-- Rahmen oben und unten, Faecher -->
	<component>
		<shape>
			<cube/>
		</shape>
		<dimension unit="mm">
			<width>312</width>
			<height>214</height>
			<depth>20</depth>
		</dimension>
		<connector name="links1" unit="mm">
			<x>0</x>
			<y>44</y>
			<z>10</z>
		</connector>
		<connector name="links2" unit="mm">
			<x>0</x>
			<y>101</y>
			<z>0</z>
		</connector>
		<connector name="links3" unit="mm">
			<x>0</x>
			<y>158</y>
			<z>10</z>
		</connector>
		<connector name="rechts1" unit="mm">
			<x>312</x>
			<y>44</y>
			<z>10</z>
		</connector>
		<connector name="rechts2" unit="mm">
			<x>312</x>
			<y>101</y>
			<z>0</z>
		</connector>
		<connector name="rechts3" unit="mm">
			<x>312</x>
			<y>158</y>
			<z>10</z>
		</connector>
		<instance name="fach-oben" tracker="3"/>
		<instance name="fach-unten" tracker="4"/>
		<instance name="rahmen-oben" tracker="5"/>
		<instance name="rahmen-unten" tracker="6"/>
	</component>
	<!-- Rahmen links und rechts -->
	<component>
		<shape>
			<cube/>
		</shape>
		<dimension unit="mm">
			<width>551</width>
			<height>220</height>
			<depth>20</depth>
		</dimension>
		<connector unit="mm" name="vorderseite1">
			<x>10</x>
			<y>50</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="vorderseite2">
			<x>541</x>
			<y>50</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="mitte1">
			<x>0</x>
			<y>107</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="mitte2">
			<x>551</x>
			<y>107</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="rueckseite1">
			<x>10</x>
			<y>164</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="rueckseite2">
			<x>541</x>
			<y>164</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="vorderseite-fach1">
			<x>175</x>
			<y>50</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="rueckseite-fach1">
			<x>175</x>
			<y>164</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="vorderseite-fach2">
			<x>375</x>
			<y>50</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="rueckseite-fach2">
			<x>375</x>
			<y>164</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="rueckwand1">
			<x>10</x>
			<y>220</y>
			<z>10</z>
		</connector>
		<connector unit="mm" name="rueckwand2">
			<x>541</x>
			<y>220</y>
			<z>10</z>
		</connector>
		<instance name="rahmen-links" tracker="7"/>
		<instance name="rahmen-rechts" tracker="8"/>
	</component>
	<!-- Rueckwand -->
	<component>
		<shape>
			<cube/>
		</shape>
		<dimension unit="mm">
			<width>352</width>
			<height>551</height>
			<depth>3</depth>
		</dimension>
		<connector unit="mm" name="links-oben">
			<x>10</x>
			<y>541</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="rechts-oben">
			<x>342</x>
			<y>541</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="links-unten">
			<x>10</x>
			<y>10</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="rechts-unten">
			<x>342</x>
			<y>10</y>
			<z>0</z>
		</connector>
		<instance name="rueckwand" tracker="9"/>
	</component>
	<!-- Bauanleitung -->
	<assembly>
		<add-component name="rahmen-unten"/>
		<rotate axis="xneg" angle="90"/>
		<add-component name="rahmen-links">
			<connect>
				<connector-ref name="vorderseite1"/>
				<connector-ref name="links1" componentRef="rahmen-unten"/>
			</connect>
			<connect>
				<connector-ref name="mitte1"/>
				<connector-ref name="links2" componentRef="rahmen-unten"/>
			</connect>
			<connect>
				<connector-ref name="rueckseite1"/>
				<connector-ref name="links3" componentRef="rahmen-unten"/>
			</connect>
		</add-component>
		<add-component name="rahmen-rechts">
			<connect>
				<connector-ref name="vorderseite2"/>
				<connector-ref name="rechts1" componentRef="rahmen-unten"/>
			</connect>
			<connect>
				<connector-ref name="mitte2"/>
				<connector-ref name="rechts2" componentRef="rahmen-unten"/>
			</connect>
			<connect>
				<connector-ref name="rueckseite2"/>
				<connector-ref name="rechts3" componentRef="rahmen-unten"/>
			</connect>
		</add-component>
		<add-component name="rahmen-oben">
			<connect>
				<connector-ref name="links1"/>
				<connector-ref name="vorderseite2" componentRef="rahmen-links"/>
			</connect>
			<connect>
				<connector-ref name="links3"/>
				<connector-ref name="rueckseite2" componentRef="rahmen-links"/>
			</connect>
			<connect>
				<connector-ref name="rechts1"/>
				<connector-ref name="vorderseite1" componentRef="rahmen-rechts"/>
			</connect>
			<connect>
				<connector-ref name="rechts3"/>
				<connector-ref name="rueckseite1" componentRef="rahmen-rechts"/>
			</connect>
		</add-component>
		<add-component name="rueckwand">
			<connect>
				<connector-ref name="rechts-unten"/>
				<connector-ref name="rueckwand1" componentRef="rahmen-links"/>
			</connect>
			<connect>
				<connector-ref name="rechts-oben"/>
				<connector-ref name="rueckwand2" componentRef="rahmen-links"/>
			</connect>
			<connect>
				<connector-ref name="links-unten"/>
				<connector-ref name="rueckwand2" componentRef="rahmen-rechts"/>
			</connect>
			<connect>
				<connector-ref name="links-oben"/>
				<connector-ref name="rueckwand1" componentRef="rahmen-rechts"/>
			</connect>
		</add-component>
		<rotate axis="xneg" angle="90"/>
		<add-component name="fach-unten">
			<connect>
				<connector-ref name="links1"/>
				<connector-ref name="vorderseite-fach2" componentRef="rahmen-links"/>
			</connect>
			<connect>
				<connector-ref name="links3"/>
				<connector-ref name="rueckseite-fach2" componentRef="rahmen-links"/>
			</connect>
			<connect>
				<connector-ref name="rechts1"/>
				<connector-ref name="vorderseite-fach1" componentRef="rahmen-rechts"/>
			</connect>
			<connect>
				<connector-ref name="rechts3"/>
				<connector-ref name="rueckseite-fach1" componentRef="rahmen-rechts"/>
			</connect>
		</add-component>
		<add-component name="fach-oben">
			<connect>
				<connector-ref name="links1"/>
				<connector-ref name="vorderseite-fach1" componentRef="rahmen-links"/>
			</connect>
			<connect>
				<connector-ref name="links3"/>
				<connector-ref name="rueckseite-fach1" componentRef="rahmen-links"/>
			</connect>
			<connect>
				<connector-ref name="rechts1"/>
				<connector-ref name="vorderseite-fach2" componentRef="rahmen-rechts"/>
			</connect>
			<connect>
				<connector-ref name="rechts3"/>
				<connector-ref name="rueckseite-fach2" componentRef="rahmen-rechts"/>
			</connect>
		</add-component>
		<rotate axis="xpos" angle="90"/>
	</assembly>
</furniture>

=== adminicg/opentracker/studierstube3/bin/apps/aeki/data/table.xml
<?xml version="1.0" encoding="UTF-8"?>
<furniture xmlns="http://www.expersite.com/AEKI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.expersite.com/AEKI ../apps/aeki/data/aeki.xsd">
  <component>
    <shape>
      <cube/>
    </shape>
    <dimension unit="mm">
      <width>1600</width>
      <height>900</height>
      <depth>35</depth>
    </dimension>
    <connector name="p_c1" unit="mm">
      <x>20</x>
      <y>20</y>
      <z>35</z>
    </connector>
    <connector name="p_c2" unit="mm">
      <x>25</x>
      <y>20</y>
      <z>35</z>
    </connector>
    <connector name="p_c3" unit="mm">
      <x>20</x>
      <y>25</y>
      <z>35</z>
    </connector>
    <connector name="p_c4" unit="mm">
      <x>1580</x>
      <y>20</y>
      <z>35</z>
    </connector>    
    <connector name="p_c5" unit="mm">
      <x>1575</x>
      <y>20</y>
      <z>35</z>
    </connector>    
    <connector name="p_c6" unit="mm">
      <x>1580</x>
      <y>25</y>
      <z>35</z>
    </connector>    
    <connector name="p_c7" unit="mm">
      <x>20</x>
      <y>880</y>
      <z>35</z>
    </connector>    
    <connector name="p_c8" unit="mm">
      <x>25</x>
      <y>880</y>
      <z>35</z>
    </connector>    
    <connector name="p_c9" unit="mm">
      <x>20</x>
      <y>875</y>
      <z>35</z>
    </connector>    
    <connector name="p_c10" unit="mm">
      <x>1580</x>
      <y>880</y>
      <z>35</z>
    </connector>    
    <connector name="p_c11" unit="mm">
      <x>1575</x>
      <y>880</y>
      <z>35</z>
    </connector>    
    <connector name="p_c12" unit="mm">
      <x>1580</x>
      <y>875</y>
      <z>35</z>
    </connector>    
    <instance name="platte"/>
  </component>
  <component>
    <shape>
      <cube/>
    </shape>
    <dimension unit="mm">
      <width>100</width>
      <height>700</height>
      <depth>100</depth>
    </dimension>
    <connector name="tb_c1" unit="mm">
      <x>5</x>
      <y>700</y>
      <z>5</z>
    </connector>
    <connector name="tb_c2" unit="mm">
      <x>10</x>
      <y>700</y>
      <z>5</z>
    </connector>
    <connector name="tb_c3" unit="mm">
      <x>5</x>
      <y>700</y>
      <z>10</z>
    </connector>
    <connector name="tb_c4" unit="mm">
      <x>50</x>
      <y>690</y>
      <z>100</z>
    </connector>
    <connector name="tb_c5" unit="mm">
      <x>50</x>
      <y>680</y>
      <z>100</z>
    </connector>
    <connector name="tb_c6" unit="mm">
      <x>100</x>
      <y>690</y>
      <z>50</z>
    </connector>
    <connector name="tb_c7" unit="mm">
      <x>100</x>
      <y>680</y>
      <z>50</z>
    </connector>
    <instance name="tb_lu"/>
    <instance name="tb_ru"/>
    <instance name="tb_lo"/>
    <instance name="tb_ro"/>
  </component>
  <component>
    <shape>
      <cube/>
    </shape>
    <dimension unit="mm">
      <width>1370</width>
      <height>100</height>
      <depth>10</depth>
    </dimension>
    <connector name="a1_c1" unit="mm">
      <x>0</x>
      <y>90</y>
      <z>5</z>
    </connector>
    <connector name="a1_c2" unit="mm">
      <x>0</x>
      <y>80</y>
      <z>5</z>
    </connector>
    <connector name="a1_c3" unit="mm">
      <x>1370</x>
      <y>90</y>
      <z>5</z>
    </connector>
    <connector name="a1_c4" unit="mm">
      <x>1370</x>
      <y>80</y>
      <z>5</z>
    </connector>
    <instance name="a1_u"/>
    <instance name="a1_o"/>
  </component>
  <component>
    <shape>
      <cube/>
    </shape>
    <dimension unit="mm">
      <width>670</width>
      <height>100</height>
      <depth>10</depth>
    </dimension>
    <connector name="a2_c1" unit="mm">
      <x>0</x>
      <y>90</y>
      <z>5</z>
    </connector>
    <connector name="a2_c2" unit="mm">
      <x>0</x>
      <y>80</y>
      <z>5</z>
    </connector>
    <connector name="a2_c3" unit="mm">
      <x>670</x>
      <y>90</y>
      <z>5</z>
    </connector>
    <connector name="a2_c4" unit="mm">
      <x>670</x>
      <y>80</y>
      <z>5</z>
    </connector>
    <instance name="a2_l"/>
    <instance name="a2_r"/>
  </component>
  <assembly>
    <add-component name="platte"/>
    <rotate axis="xneg" angle="90"/>    
    <add-component name="tb_lu">
      <connect>
        <connector-ref name="tb_c1"/>
        <connector-ref name="p_c1" componentRef="platte"/>
      </connect>
      <connect>
        <connector-ref name="tb_c2"/>
        <connector-ref name="p_c2" componentRef="platte"/>
      </connect>
      <connect>
        <connector-ref name="tb_c3"/>
        <connector-ref name="p_c3" componentRef="platte"/>
      </connect>
    </add-component>
    <add-component name="tb_ru">
      <connect>
        <connector-ref name="tb_c1"/>
        <connector-ref name="p_c4" componentRef="platte"/>
      </connect>
      <connect>
        <connector-ref name="tb_c2"/>
        <connector-ref name="p_c6" componentRef="platte"/>
      </connect>
      <connect>
        <connector-ref name="tb_c3"/>
        <connector-ref name="p_c5" componentRef="platte"/>
      </connect>
    </add-component>
    <add-component name="tb_lo">
      <connect>
        <connector-ref name="tb_c1"/>
        <connector-ref name="p_c7" componentRef="platte"/>
      </connect>
      <connect>
        <connector-ref name="tb_c2"/>
        <connector-ref name="p_c9" componentRef="platte"/>
      </connect>
      <connect>
        <connector-ref name="tb_c3"/>
        <connector-ref name="p_c8" componentRef="platte"/>
      </connect>
    </add-component>
    <add-component name="tb_ro">
      <connect>
        <connector-ref name="tb_c1"/>
        <connector-ref name="p_c10" componentRef="platte"/>
      </connect>
      <connect>
        <connector-ref name="tb_c2"/>
        <connector-ref name="p_c11" componentRef="platte"/>
      </connect>
      <connect>
        <connector-ref name="tb_c3"/>
        <connector-ref name="p_c12" componentRef="platte"/>
      </connect>
    </add-component>
    <add-component name="a1_u">
      <connect>
        <connector-ref name="a1_c1"/>
        <connector-ref name="tb_c6" componentRef="tb_lu"/>
      </connect>
      <connect>
        <connector-ref name="a1_c2"/>
        <connector-ref name="tb_c7" componentRef="tb_lu"/>
      </connect>
      <connect>
        <connector-ref name="a1_c3"/>
        <connector-ref name="tb_c4" componentRef="tb_ru"/>
      </connect>
      <connect>
        <connector-ref name="a1_c4"/>
        <connector-ref name="tb_c5" componentRef="tb_ru"/>
      </connect>
    </add-component>
    <add-component name="a1_o">
      <connect>
        <connector-ref name="a1_c1"/>
        <connector-ref name="tb_c4" componentRef="tb_lo"/>
      </connect>
      <connect>
        <connector-ref name="a1_c2"/>
        <connector-ref name="tb_c5" componentRef="tb_lo"/>
      </connect>
      <connect>
        <connector-ref name="a1_c3"/>
        <connector-ref name="tb_c6" componentRef="tb_ro"/>
      </connect>
      <connect>
        <connector-ref name="a1_c4"/>
        <connector-ref name="tb_c7" componentRef="tb_ro"/>
      </connect>
    </add-component>
    <add-component name="a2_l">
      <connect>
        <connector-ref name="a2_c1"/>
        <connector-ref name="tb_c4" componentRef="tb_lu"/>
      </connect>
      <connect>
        <connector-ref name="a2_c2"/>
        <connector-ref name="tb_c5" componentRef="tb_lu"/>
      </connect>
      <connect>
        <connector-ref name="a2_c3"/>
        <connector-ref name="tb_c6" componentRef="tb_lo"/>
      </connect>
      <connect>
        <connector-ref name="a2_c4"/>
        <connector-ref name="tb_c7" componentRef="tb_lo"/>
      </connect>
    </add-component>
    <add-component name="a2_r">
      <connect>
        <connector-ref name="a2_c1"/>
        <connector-ref name="tb_c6" componentRef="tb_ru"/>
      </connect>
      <connect>
        <connector-ref name="a2_c2"/>
        <connector-ref name="tb_c7" componentRef="tb_ru"/>
      </connect>
      <connect>
        <connector-ref name="a2_c3"/>
        <connector-ref name="tb_c4" componentRef="tb_ro"/>
      </connect>
      <connect>
        <connector-ref name="a2_c4"/>
        <connector-ref name="tb_c5" componentRef="tb_ro"/>
      </connect>
    </add-component>
    <rotate axis="xpos" angle="180"/>
  </assembly>
</furniture>

=== adminicg/opentracker/studierstube3/bin/apps/aeki/data/smallbox.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.2 U (http://www.xmlspy.com) by Gerhard (Vienna University of Technology) -->
<furniture xmlns="http://www.expersite.com/AEKI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.expersite.com/AEKI
..\apps\aeki\data\aeki.xsd">
	<component>
		<shape>
			<cube/>
		</shape>
		<dimension unit="mm">
			<width>330</width>
			<height>330</height>
			<depth>4</depth>
		</dimension>
		<connector unit="mm" name="board1-left">
			<x>25</x>
			<y>66</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="board1-middle">
			<x>146</x>
			<y>70</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="board1-right">
			<x>267</x>
			<y>66</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="board2-left">
			<x>25</x>
			<y>130</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="board2-middle">
			<x>146</x>
			<y>134</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="board2-right">
			<x>267</x>
			<y>130</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="board3-left">
			<x>25</x>
			<y>195</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="board3-middle">
			<x>146</x>
			<y>199</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="board3-right">
			<x>267</x>
			<y>195</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="board4-left">
			<x>25</x>
			<y>259</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="board4-middle">
			<x>146</x>
			<y>263</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="board4-right">
			<x>267</x>
			<y>259</y>
			<z>0</z>
		</connector>
		<instance name="left" tracker="3"/>
		<instance name="right" tracker="4"/>
	</component>
	<component>
		<shape>
			<cube/>
		</shape>
		<dimension unit="mm">
			<width>241</width>
			<height>324</height>
			<depth>4</depth>
		</dimension>
		<connector unit="mm" name="left1">
			<x>0</x>
			<y>25</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="left2">
			<x>0</x>
			<y>145</y>
			<z>4</z>
		</connector>
		<connector unit="mm" name="left3">
			<x>0</x>
			<y>267</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="right1">
			<x>241</x>
			<y>25</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="right2">
			<x>241</x>
			<y>145</y>
			<z>4</z>
		</connector>
		<connector unit="mm" name="right3">
			<x>241</x>
			<y>267</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="back1">
			<x>76</x>
			<y>320</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="back2">
			<x>163</x>
			<y>320</y>
			<z>0</z>
		</connector>
		<instance name="board1" tracker="5"/>
		<instance name="board2" tracker="6"/>
		<instance name="board3" tracker="7"/>
		<instance name="board4" tracker="8"/>
	</component>
	<component>
		<shape>
			<cube/>
		</shape>
		<dimension unit="mm">
			<width>119</width>
			<height>290</height>
			<depth>4</depth>
		</dimension>
		<connector unit="mm" name="leftw1">
			<x>15</x>
			<y>45</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="lefwt2">
			<x>15</x>
			<y>110</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="leftw3">
			<x>15</x>
			<y>174</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="leftw4">
			<x>15</x>
			<y>238</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="rightw1">
			<x>101</x>
			<y>45</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="rightw2">
			<x>101</x>
			<y>110</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="rightw3">
			<x>101</x>
			<y>174</y>
			<z>0</z>
		</connector>
		<connector unit="mm" name="rightw4">
			<x>101</x>
			<y>238</y>
			<z>0</z>
		</connector>
		<instance name="back" tracker="9"/>
	</component>
	<assembly>
		<add-component name="left"/>
		<!--<rotate axis="xneg" angle="90"/>-->
		<add-component name="board1">
			<connect>
				<connector-ref name="left1"/>
				<connector-ref name="board1-left" componentRef="left"/>
			</connect>
			<connect>
				<connector-ref name="left2"/>
				<connector-ref name="board1-middle" componentRef="left"/>
			</connect>
			<connect>
				<connector-ref name="left3"/>
				<connector-ref name="board1-right" componentRef="left"/>
			</connect>
		</add-component>
		<add-component name="board2">
			<connect>
				<connector-ref name="left1"/>
				<connector-ref name="board2-left" componentRef="left"/>
			</connect>
			<connect>
				<connector-ref name="left2"/>
				<connector-ref name="board2-middle" componentRef="left"/>
			</connect>
			<connect>
				<connector-ref name="left3"/>
				<connector-ref name="board2-right" componentRef="left"/>
			</connect>
		</add-component>
		<add-component name="board3">
			<connect>
				<connector-ref name="left1"/>
				<connector-ref name="board3-left" componentRef="left"/>
			</connect>
			<connect>
				<connector-ref name="left2"/>
				<connector-ref name="board3-middle" componentRef="left"/>
			</connect>
			<connect>
				<connector-ref name="left3"/>
				<connector-ref name="board3-right" componentRef="left"/>
			</connect>
		</add-component>
		<add-component name="board4">
			<connect>
				<connector-ref name="left1"/>
				<connector-ref name="board4-left" componentRef="left"/>
			</connect>
			<connect>
				<connector-ref name="left2"/>
				<connector-ref name="board4-middle" componentRef="left"/>
			</connect>
			<connect>
				<connector-ref name="left3"/>
				<connector-ref name="board4-right" componentRef="left"/>
			</connect>
		</add-component>
		<add-component name="right">
			<connect>
				<connector-ref name="board1-left"/>
				<connector-ref name="right1" componentRef="board1"/>
			</connect>
			<connect>
				<connector-ref name="board1-right"/>
				<connector-ref name="right3" componentRef="board1"/>
			</connect>
			<connect>
				<connector-ref name="board4-left"/>
				<connector-ref name="right1" componentRef="board4"/>
			</connect>
			<connect>
				<connector-ref name="board4-right"/>
				<connector-ref name="right3" componentRef="board4"/>
			</connect>
		</add-component>
		<rotate axis="xpos" angle="90"/>
		<rotate axis="zpos" angle="90"/>
		<add-component name="back">
			<connect>
				<connector-ref name="leftw1"/>
				<connector-ref name="back1" componentRef="board1"/>
			</connect>
			<connect>
				<connector-ref name="rightw1"/>
				<connector-ref name="back2" componentRef="board1"/>
			</connect>
			<connect>
				<connector-ref name="leftw4"/>
				<connector-ref name="back1" componentRef="board4"/>
			</connect>
			<connect>
				<connector-ref name="rightw4"/>
				<connector-ref name="back2" componentRef="board4"/>
			</connect>
		</add-component>
		<rotate axis="zpos" angle="90"/>
	</assembly>
</furniture>
